### PR TITLE
adding elliotharmon

### PR DESCRIPTION
**Pull request by elliotharmon**

### CODE REVIEW

**Comment by dirkcuys** [comment]
Hey @elliotharmon - glad you're joining us! I manually added your signup data, so I'm closing this pull request.

I'm still trying to figure out how to make it easy to keep pull requests for signup seperate from updates to your own course. Currently that requires getting into the details of git branches and that's probably too messy for most people. Do you maybe have any ideas?

Cheers
Dirk

**Comment by iamtjg** [comment]
One idea, people could open an issue with their info to be added

-Tim

**Comment by dirkcuys** [comment]
That can work for the signup. Ideally people would also be able to contribute to the course content itself, things like FAQs or helping with the content like you are helping :) Although that is easy to do if you edit in the GitHub interface.

For now I think this is fine, manually adding signup data when I need to isn't a lot of work and I like the idea of people getting a feel for what it is like working on GitHub pages right from the start.

**Comment by elliotharmon** [comment]
Why not have participants create two separate branches, one for the shared course site and one for their own personal course site? That feels like the more natural workflow anyway --- in playing with my own page, I'll make edits that aren't intended for the _big_ course (that's what I was doing here, messing with the URL structure so that I could run it on Jekyll on my own computer).

**Comment by dirkcuys** [comment]
Yes, that is the most natural workflow for me too. I'm concerned that people without any Git/version control experience will find that too hard?

**Comment by elliotharmon** [comment]
I suppose to do it that way, people need to be running Jekyll on their own machines. Since (I think?) the branch has to be called gh-pages to view it on github.io.

**Comment by dirkcuys** [comment]
If they use the gh-pages branch to work in and another branch to submit
pull requests to the main repository they won't need to run Jekyll locally,
but it gets complicated...

**Comment by billymeinke** [comment]
A visual representation to whatever workflow ends up being recommended to
newcomers would be really useful to have.

Anyone want to begin mocking one up and we can iterate? There are some
holes in my own understanding of forking/branching, but I'm willing to help
refine.

On Thu, Aug 21, 2014 at 11:03 AM, Dirk Uys notifications@github.com wrote:

> If they use the gh-pages branch to work in and another branch to submit
> pull requests to the main repository they won't need to run Jekyll
> locally,
> but it gets complicated...
> 
> On Thu, Aug 21, 2014 at 1:01 PM, elliotharmon notifications@github.com
> wrote:
> 
> > I suppose to do it that way, people need to be running Jekyll on their
> > own
> > machines. Since (I think?) the branch has to be called gh-pages to view
> > it
> > on github.io.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/p2pu/jekyll-course-experiment/pull/33#issuecomment-52958074>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/p2pu/jekyll-course-experiment/pull/33#issuecomment-52958372
> .

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / web
http://billymeinke.wordpress.com/aboutme/

**Pull request closed without merging**
