### PR TITLE
Delete CNAME

### PR DESCRIPTION
**Pull request by TerriatTaft**
This is to delete the CNAME

### CODE REVIEW

**Comment by TerriatTaft** [comment]
Added a logo, changed the title, changed the background color

**Comment by TerriatTaft** [comment]
Added links to 8 tutorials that we love

**Comment by TerriatTaft** [comment]
to update the file

**Comment by dirkcuys** [comment]
Hey @TerriatTaft 
You don't need to send a PR to get update your own site (https://terriattaft.github.io/OneSearchTutorial/). I'm closing this PR, but feel free to send a message if you'd like help.

**Pull request closed without merging**
