### PR TITLE
gh links helper UX improved

### PR DESCRIPTION
**Pull request by ercchy**
Changing UX for the github username set. The result is on the screenshot:

new_ux_for_gh_username

### CODE REVIEW

**Comment by dirkcuys** [comment]
Thanks @ercchy - this looks good. Asking users for their username seperately is a good idea. How will users get to that input if they are on a different page, or would it then just use the inline text input?

**Comment by ercchy** [comment]
The links still have the set input on each, and they can set it on whichever link, shall they need to.

**Comment by dirkcuys** [comment]
Sorry, I was being lazy, should have checked that and not ask :)

**Comment by ercchy** [comment]
Nah, I would have done that too :). It is way easier to ask than to merge into your own branch and check.

**Comment by dirkcuys** [comment]
Actually did the 'merge into your own branch and check.', but didn't check
everything :)

If you set up a remote, it's actually very little effort to do

**Pull request merged**
