### PR TITLE
Sign up data for course

### PR DESCRIPTION
**Pull request by patterbh**

### CODE REVIEW

**Comment by dirkcuys** [comment]
This seems like the same pull as one I merged, your signup should already be there now :)

**Comment by patterbh** [comment]
Thanks, Dirk.  I can't seem to view my course.

**Comment by dirkcuys** [comment]
It should be at http://patterbh.github.io/course-in-a-box/, but it doesn't show? I checked out your code locally and it doesn't seem like Jekyll has any problems with it? Did you receive any error messages when you made changes to the repository? I wonder if we can ask someone from GitHub to have a look?

**Comment by dirkcuys** [comment]
Just got a reply back from GitHub, seems like you need to verify your email address and then make an edit before you'll be able to see your course.

**Pull request closed without merging**
