### PR TITLE
Update course.yml

### PR DESCRIPTION
**Pull request by tellio**

### CODE REVIEW

**Comment by dirkcuys** [comment]
Hey Terry! Pulled in your changes, seems like the photo URL doesn't point at an image but at a web page. I'll update it to point at https://farm8.staticflickr.com/7301/13982521190_ce0d7c5734_s.jpg

**Comment by ercchy** [comment]
Yay... commit! Your firs commit @tellio?

**Comment by tellio** [comment]
Yes, been promising to play with git for the longest time.  Now that I have
such good support I fear no failure.

**Comment by tellio** [comment]
Thank you so much.  I really am a trained monkey on this kind of stuff.
Without your awesome instructions, I would have been totally lost as
opposed to only partly lost.  Just wanted you know who you are dealing with
here--a n00b.

Terry

**Comment by ercchy** [comment]
Ah git, it is a love hate relationship we have. Well it became mostlly love, now that I got used to it, but it took me way too long. Once u get the concept the basic stuff becomes very easy.

But let me tell you, you did this like a boss! 

I am teaching git to the girls at my coding club and sometimes it takes us days before we are able to send first pull request. So, good job.

I like that you find the instructions useful, but if there is anything that we could do to make it even more simple, I would be happy to listen.

And you know, Dirk and I are always here to help, all you have to do is call us :).

**Pull request merged**
