### PR TITLE
fixing the calendar rendering

### PR DESCRIPTION
**Pull request by ercchy**
- Using google API v3 to access the calendar and render all the data from within.
- Limiting calendar scripts to be used only on index.html

### CODE REVIEW

**Comment by dirkcuys** [comment]
Hey @ercchy looks good! Good thinking on using the API and well done on getting it done this quick!

Before I merge, can I ask a big favour... Could you please undo the indentation changes to _layouts/base.html? I don't disagree with them, but indentation changes are a recipe for merge conflicts and a lot of people already forked the course.

**Comment by ercchy** [comment]
Sure I can clean it up, I use Pycharm and it does it automaticaly

**Comment by dirkcuys** [comment]
Thanks! Sorry for being nit-picky.

**Comment by dirkcuys** [comment]
Hope you don't mind, did my own nit picking, didn't see your updates before I did so :(

**Pull request closed without merging**
