### PR TITLE
Update course.yml

### PR DESCRIPTION
**Pull request by SchuylerTowne**
Adding myself to the peeps

### CODE REVIEW

**Comment by dirkcuys** [comment]
Hey, welcome!

**Comment by SchuylerTowne** [comment]
Thanks! :)

**Comment by dirkcuys** [comment]
Things are pretty rough and still developing. Feel free to poke around and make suggestions or changes.

**Comment by mozzadrella** [comment]
I LOVE EVERYTHING ABOUT THIS. @SchuylerTowne you are the bestest of guineapigs!

**Comment by SchuylerTowne** [comment]
Hahaha! I'm very very excited to be said guineapig :)

**Pull request merged**
